### ISSUE TITLE
there's a lot more…

### ISSUE THREAD

**Issue by derhuerst** [dbopendata/db-ice-portal-api#1]
See https://gist.github.com/derhuerst/6ed050af540d34cf0612909564400eda. This has been captured when the ICE trains were inside Berlin Central Station. Credits to @juliuste.

**Comment by derhuerst** [comment]
The most interesting stuff seems to be `/tripInfo`: https://gist.github.com/derhuerst/d2c3419d627d5fe43d5509a983d1f259/27c40125c4721bd7e15a2e6a12be2fd4d09d71c2#file-tripinfo-1-http

**Comment by derhuerst** [comment]
Also, [in `/status`, there is a value `SERVICE_LIMIT` for `serviceLevel`](https://gist.github.com/derhuerst/d2c3419d627d5fe43d5509a983d1f259/27c40125c4721bd7e15a2e6a12be2fd4d09d71c2#file-status-2-http-L26).

**Comment by highsource** [comment]
Yes, there's more. :) But not everything will be made open data. We have a principal (not formal yet) OK to publish `/status` under an Open Data licennse (like CC BY 4.0).

`tripInfo` will not be made Open Data at the moment as it has data not owned/controlled by DB Fv. The same for POIs, this is was bought data where we have no right to make it open data. Other things are probably not of much interest, so we'll start with `/status` and then see how it develops.

**Comment by highsource** [comment]
The Swagger spec is WIP, there are more values `serviceLimit`, I'll add them later on.
