### ISSUE TITLE
Documentation for tripInfo API missing

### ISSUE THREAD

**Issue by Dunedan** [dbopendata/db-ice-portal-api#3]
There is also a `tripInfo` API with lots of interesting information, although it's not documented here. Can you please add documentation for it?!

**Comment by highsource** [comment]
Would you give an example? That's not in the official document, probably some HaFas leftover.

**Comment by Dunedan** [comment]
It's the API returning the data used in the portal to show upcoming stops, delays etc and is available at http://ice.portal2/api1/rs/tripInfo

The attached example is from yesterdays ICE 75 trip: [tripinfo-example.json.txt](https://github.com/dbopendata/db-ice-portal-api/files/546489/tripinfo-example.json.txt)

**Comment by highsource** [comment]
Ah, OK, that one.

`tripinfo` will not be an official API, unfortunately. It is backed by systems which don't release data as open data at the moment. So ICE Portal can't do that either (they don't own the data). Technically, nothing prevents you from using that endpoint but it won't be legal/official.
